obstacle_range: 4.0
raytrace_range: 5.0
footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

observation_sources: laser_scan_sensor point_cloud_sensor

# laser_scan_sensor: {sensor_frame: pico_zense_depth_frame , data_type: LaserScan, topic: /pico_scan, marking: true, clearing: true}
laser_scan_sensor: {sensor_frame: laser , data_type: LaserScan, topic: /scan, marking: true, clearing: true}
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}